// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkdowzhdscozewycsouk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZG93emhkc2NvemV3eWNzb3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzYyMzcsImV4cCI6MjA2MzUxMjIzN30.rfn004yI4xoA0DZe-5r_2J3KW4peXO1p2OF8IDRXbWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);